import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class FrmFactura extends javax.swing.JInternalFrame {
    private JTextArea txtFactura;
    private JTextField txtNombreCliente;
    private JButton btnBuscar;
    /**
     * Creates new form FrmFactura
     */
    public FrmFactura() {
        initComponents();
        
    }
    private void initComponents() {
        setTitle("Factura de Viaje");
        setClosable(true);
        setSize(500, 400);
        setLayout(null);

        JLabel lblNombre = new JLabel("Nombre del cliente:");
        lblNombre.setBounds(20, 20, 150, 25);
        add(lblNombre);

        txtNombreCliente = new JTextField();
        txtNombreCliente.setBounds(170, 20, 200, 25);
        add(txtNombreCliente);

        btnBuscar = new JButton("Generar factura");
        btnBuscar.setBounds(380, 20, 90, 25);
        add(btnBuscar);

        txtFactura = new JTextArea();
        txtFactura.setEditable(false);
        JScrollPane scroll = new JScrollPane(txtFactura);
        scroll.setBounds(20, 60, 450, 280);
        add(scroll);

        btnBuscar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                generarFacturaPorNombre(txtNombreCliente.getText().trim());
            }
        });
    }

    private void generarFacturaPorNombre(String nombreBuscado) {
        Viaje encontrado = null;

        for (Viaje v : FrmViajes.listaViajes) {
            if (v.getNombreCliente().equalsIgnoreCase(nombreBuscado)) {
                encontrado = v;
                break;
            }
        }

        if (encontrado != null) {
            String factura = """
                    ----------------------------------------
                                AGENCIA DE VIAJES
                              FACTURA DE RESERVA
                    ----------------------------------------

                    Cliente: %s

                    Destino: %s
                    Fecha: %s
                    Plan: %s
                    Costo: $%.2f

                    ----------------------------------------
                    ¡Gracias por viajar con nosotros!
                    """.formatted(
                    encontrado.getNombreCliente(),
                    encontrado.getDestino(),
                    encontrado.getFecha(),
                    encontrado.getPlan(),
                    encontrado.getCosto()
            );
            txtFactura.setText(factura);
        } else {
            txtFactura.setText("No se encontró una reserva con ese nombre.");
        }
    }
    

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("FACTURAS");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("BUSCAR");

        lblNombre.setText("Nombre del Cliente: ");

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
