
public class FrmPrincipal extends javax.swing.JFrame {
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem generarFactura;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registrocliente = new javax.swing.JMenuItem();
        tablaClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        registroviaje = new javax.swing.JMenuItem();
        tablaViaje = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuFactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jMenu1.setText("CLIENTES");

        registrocliente.setText("Registro Clientes");
        registrocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroclienteActionPerformed(evt);
            }
        });
        jMenu1.add(registrocliente);

        tablaClientes.setText("Lista Clientes");
        tablaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaClientesActionPerformed(evt);
            }
        });
        jMenu1.add(tablaClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("VIAJES");

        registroviaje.setText("Registro Viajes");
        registroviaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroviajeActionPerformed(evt);
            }
        });
        jMenu2.add(registroviaje);

        tablaViaje.setText("Tabla Reservas");
        tablaViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaViajeActionPerformed(evt);
            }
        });
        jMenu2.add(tablaViaje);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("FACTURAS");

        menuFactura.setText("Buscar Facturas");
        menuFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturaActionPerformed(evt);
            }
        });
        jMenu4.add(menuFactura);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroclienteActionPerformed

        FrmClientes frm = new FrmClientes(); 
        escritorio.add(frm);
        frm.setVisible(true);
        setClosable(true);
// TODO add your handling code here:
    }//GEN-LAST:event_registroclienteActionPerformed

    private void registroviajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroviajeActionPerformed
        FrmViajes frm = new FrmViajes(); 
        escritorio.add(frm);
        frm.setVisible(true);
        setClosable(true);
// TODO add your handling code here:
    }//GEN-LAST:event_registroviajeActionPerformed

    private void tablaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaClientesActionPerformed
        FrmTablaClientes tabla = new FrmTablaClientes();
        escritorio.add(tabla);
        tabla.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_tablaClientesActionPerformed

    private void tablaViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaViajeActionPerformed
        FrmTablaViajes tabla = new FrmTablaViajes();
        escritorio.add(tabla);
        tabla.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_tablaViajeActionPerformed

    private void menuFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturaActionPerformed
         FrmFactura factura = new FrmFactura();
        escritorio.add(factura);
        factura.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_menuFacturaActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuFactura;
    private javax.swing.JMenuItem registrocliente;
    private javax.swing.JMenuItem registroviaje;
    private javax.swing.JMenuItem tablaClientes;
    private javax.swing.JMenuItem tablaViaje;
    // End of variables declaration//GEN-END:variables

    private void setClosable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
