
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
public class FrmViajes extends javax.swing.JInternalFrame {
    public static List<Viaje> listaViajes = new ArrayList<>();
    public static ArrayList<Cliente> listaClientes = new ArrayList<>();



   
    public FrmViajes() {
        initComponents();
        String[] columnas = {"Destino", "Fecha", "Plan", "Costo"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        TablaViaje.setModel(modelo);
        
        comboCliente.removeAllItems();
        for (Cliente c : FrmClientes.listaClientes) {
        comboCliente.addItem(c.getNombre());
}
    }
    
    private double calcularPrecio(String plan) {
    switch (plan) {
        case "Individual":
            return 500000;
        case "Dos Personas":
            return 800000;
        case "Familiar":
            return 1200000;
        default:
            return 0;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPlan = new javax.swing.ButtonGroup();
        lblCliente = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblPlan = new javax.swing.JLabel();
        rbtIndividual = new javax.swing.JRadioButton();
        rbtDosPersonas = new javax.swing.JRadioButton();
        rbtFamiliar = new javax.swing.JRadioButton();
        btnRegistrar = new javax.swing.JButton();
        TablaViajes = new javax.swing.JScrollPane();
        TablaViaje = new javax.swing.JTable();

        setClosable(true);
        setTitle("RESERVAR VIAJE");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente.setText("Cliente: ");

        comboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Destino:");

        comboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coveñas", "San Andres", "Santa Marta", " " }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha: ");

        txtFecha.setText("jTextField1");

        lblPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlan.setText("Plan: ");

        grupoPlan.add(rbtIndividual);
        rbtIndividual.setText("Individual");

        grupoPlan.add(rbtDosPersonas);
        rbtDosPersonas.setText("Dos Persona");

        grupoPlan.add(rbtFamiliar);
        rbtFamiliar.setText("Familiar");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        TablaViaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaViajes.setViewportView(TablaViaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtIndividual))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCliente)
                            .addGap(33, 33, 33)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnRegistrar)
                            .addGap(1, 1, 1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtFamiliar)
                            .addComponent(rbtDosPersonas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(TablaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblPlan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(rbtIndividual)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtDosPersonas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtFamiliar))
                    .addComponent(TablaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         String destino = (String) comboDestino.getSelectedItem();
    String fecha = txtFecha.getText();
    String plan = "";

    if (rbtIndividual.isSelected()) {
        plan = "Individual";
    } else if (rbtDosPersonas.isSelected()) {
        plan = "Dos Personas";
    } else if (rbtFamiliar.isSelected()) {
        plan = "Familiar";
    }

    double precio = calcularPrecio(plan);
    String cliente = (String) comboCliente.getSelectedItem(); // <-- AÑADIDO

    // Crear objeto viaje y añadirlo a la lista
    Viaje viaje = new Viaje(destino, fecha, plan, precio, cliente); // <-- AÑADIDO cliente
    listaViajes.add(viaje);

    // Agregar fila a la tabla
    DefaultTableModel modelo = (DefaultTableModel) TablaViaje.getModel();
    modelo.addRow(new Object[]{destino, fecha, plan, precio});

    // Limpiar campos
    txtFecha.setText("");
    grupoPlan.clearSelection();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaViaje;
    private javax.swing.JScrollPane TablaViajes;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.ButtonGroup grupoPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JRadioButton rbtDosPersonas;
    private javax.swing.JRadioButton rbtFamiliar;
    private javax.swing.JRadioButton rbtIndividual;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
